### ISSUE TITLE
Maybe a countdown enhancement

### ISSUE THREAD

**Issue by hsynksahin** [Destiny-Ed/date_count_down#2]
For one of project I needed a countdown that only shows the biggest time stuff (day, hour etc.). Lucky that i found this repository and like it. I made little changes on it to fit my request now it works like '23 HOURS LEFT' but it still refreshes this text every second so its not optimized. I had what i wanted anyways but if you will add an alike feature here the codes after I changed
[codes.zip](https://github.com/Destiny-Ed/date_count_down/files/8879237/codes.zip)

**Comment by Destiny-Ed** [comment]
Hello Destanci

You can create a pull request, and I will look into that and merge.
